### ISSUE TITLE
User profiles

### ISSUE THREAD

**Issue by aaronchantrill** [NaomiProject/Naomi#378]
## Detailed Description

Instead of having a single user in the profile, I would like to have multiple user profiles for different users.

## Context

I have been experimenting with speaker identification systems. Once the speaker has been identified, Naomi can address the user by name. I realize that some skills make more sense on an individual basis. For example, when using the "[Check Email](https://github.com/NaomiProject/Naomi/tree/naomi-dev/plugins/speechhandler/check_email)" skill, there should be an email address associated with the individual user. Naomi will check the email of the user who asks. This could also be helpful when using the "[Respond to Email](https://github.com/NaomiProject/Naomi/tree/naomi-dev/plugins/notificationclient/respondtoemail)" skill, where Naomi's responses could be tailored to the individual based on the email address it was received from.

For example, I would like to have an app that makes grocery lists for me, so that all I have to do is tell Naomi to add things to my list. Then when I get to the store, I can text Naomi and get my list which might be different the lists of other members of the household.

## Possible Implementation

In profile.yml:
```
users:
    aaron:
        firstname: aaron
        lastname: chantrill
        primary_email: aaronc@projectnaomi.com
        respond_to:
        - 3045551212@vtext.com
        - aaronc@projectnaomi.com
    eartha:
        firstname: eartha
        lastname: kitt
        primary_email: eartha@projectnaomi.com
```
I'm still thinking about it.

In addition, I would like to be able to assign Naomi its own email address, where "Respond to Email" would receive requests and send responses.
